name: Windows Runner
on: [workflow_dispatch]
jobs:
  SSH:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: Setup ssh session
      uses: mxschmitt/action-tmate@v3
